### ISSUE TITLE
Missing columns in RGB565 but present in RGB8888

### ISSUE THREAD

**Issue by toneck** [bitbank2/JPEGDEC#72]
When trying to convert an image using the _user provided buffer_ it works ok for the RGB8888, but has missing columns for RGB565. After some testing it happens when using the draw callback as well.

**To Reproduce**

1. clone repo
2. modify linux/main.c: ucPixelType = RGB565_BIG_ENDIAN //or little endian
3. convert a file
4. image with column mising
![image](https://github.com/bitbank2/JPEGDEC/assets/72277701/71adf57a-9105-4fbf-8859-cf9af49dea55)
also some columns are switched. Notably columns that start at multiple of 128 on the x. Column 640->512 -> 384 -> 256 -> 128 ->0

**Expected behavior**
A clear image as it appears with RGB8888
![image](https://github.com/bitbank2/JPEGDEC/assets/72277701/0ae8bcce-8feb-4ce8-8a79-bc8a9a7feb93)

**Additional context**
I was using your library to convert some images on an ESP32-cam since last year. (it was significantly faster than the provided library from Espressif) I needed RGB888 so I modified the code to produce RGB888 instead of RGB565.
I noticed in January that you added RGB888 and tried the linux/main example. I saw you added the option of supplying a buffer from the user. Hoping to skip the drawcallback I tried your example on pc first and it worked. I wanted to test my code with rgb565 to see if I get a higher fps so I tried to change from RGB8888 to RGB565 and it kept giving me empty columns. I tried using the callback function to save the data to a buffer and save that to a file. The resulted file had no missing columns.
I tried looking over the jpeg.inl to locate the problem, but I didn't notice anything wrong. I presumed I was doing something wrong so I stayed with the callback and RGB8888.
I noticed the issue #69 and thought it may be similar, but the latest fix didn't work for me.

Today I decided to try using a callback function again, but now I see the columns when using the callback and when using the buffer. I'm not sure if before I did something different or if this is a new bug.
To test that I didn't do anything wrong, I tried a few previous commits, using the same callback function that just saves everything into a buffer. All tests are done with the tulips header image.
Commit e6293f0970527024f772adf455447a413e344777 works as intended.
Commit 6dd03753c800a686c86fdf502bf4116890998bc5 segfaults after a few rows of decoding the image in RGB565. 
Commit f6a46aa42c5c7e131fb3389a1516876e8ec23ae8 outputs columns.

Also, there is no difference between RGB 565 little or big endian for the bugged commits, they both output little endian. This problem doesn't appear in e6293f0970527024f772adf455447a413e344777.

**Comment by toneck** [comment]
After trying some more commits, 2dbb61c8a30158e94924df04af60396c5680a72b already has this bug, which is the next commit after e6293f0970527024f772adf455447a413e344777 (which doesn't).
Therefore the bug was introduced in 2dbb61c8a30158e94924df04af60396c5680a72b

**Comment by bitbank2** [comment]
Are you running the code on an ESP32 or ESP32-S3? If the S3, then it looks like a memory alignment issue with the output buffer.

**Comment by toneck** [comment]
I also think it's an alignment issue.

I didn't have my esp on hand, so I ran it on my phone in termux (aarch64)

That being said, I am quite sure I had this problem on my laptop (64bit intel) about a month ago.

I'll be able to test it on the esp in about 2 hours

**Comment by toneck** [comment]
Ok, so, I was able to test it both on my laptop (amd64) and on my esp32.
It appears to work on both of them. The problem seems to be only on aarch64. 
I am curious if it would appear on a raspberry pi.

**Comment by bitbank2** [comment]
Thanks for narrowing it down; I'll investigate.

**Comment by bitbank2** [comment]
Fixed the NEON code. Please confirm.

**Comment by toneck** [comment]
I didn't have time yesterday, but I managed to test it today.
The columns are not missing anymore.
Thanks for the help

On the other hand, the bug with the RGB565 not outputing big endian is still present.
I did some tests and this bug affects just decoding at full scale.
Decoding at half, quarter or eighth will output little endian for RGB565_LITTLE_ENDIAN and big endian for RGB565_BIG_ENDIAN
Decoding at full size will always output little endian, even for RGB565_BIG_ENDIAN.

**Comment by toneck** [comment]
Should I close this bug and open a different bug for that one?

**Comment by bitbank2** [comment]
I can fix that issue here too. I'll get to it today.

**Comment by bitbank2** [comment]
Please give it a try now

**Comment by toneck** [comment]
Thank you for your help, unfortunately, it is still present

**Comment by bitbank2** [comment]
interesting; on MacOS that doesn't give a warning or error. I'll fix it - thanks.

**Comment by toneck** [comment]
I think the problem is that the variable is declared as _uint16x8_t_
uint16x8_t u168Temp, u168Temp2;
it appears that _vrev16q_u8_ expects a _uint8x16_t_ : [link](https://developer.arm.com/architectures/instruction-sets/intrinsics/vrev16q_u8)

**Comment by bitbank2** [comment]
yes, of course I see the issue, but some compilers allow you to pass 128-bit registers without making a fuss about the implied type.

**Comment by toneck** [comment]
Here is the gcc that I use if it helps:

I use a chroot ubuntu environment in termux, this is the gcc verision that I use
![image](https://github.com/bitbank2/JPEGDEC/assets/72277701/31fd1f5f-d497-47a3-bf82-9fb89a64dc90)


I tried the gcc compiler that is present in termux (not in the chroot) and it compiles, but the bigendian output is still little endian.
![image](https://github.com/bitbank2/JPEGDEC/assets/72277701/e104a53f-8a86-4f55-b789-e1e3e553598f)

**Comment by bitbank2** [comment]
ok, I added the requisite vreinterpretq_xx_xx wrappers. Please let me know if your compiler accepts it now.

**Comment by bitbank2** [comment]
Is the fix working for you?

**Comment by toneck** [comment]
Hi again,
Sorry for the very late reply. I got busy and forgot.

I just checked all three formats RGB565 little and BIG endian and RGB888 for all scalings and they work as they should.

Thank you for your help
