### ISSUE TITLE
V1.7.0 fails to build

### ISSUE THREAD

**Issue by mariusGundersen** [bitbank2/JPEGDEC#89]
I get the following error with the latest version:

```
/home/runner/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: .pio/build/release/lib7b2/libJPEGDEC.a(JPEGDEC.cpp.o):(.literal._ZL12JPEGPutMCU22P14jpeg_image_tagii+0x4): undefined reference to `s3_ycbcr_convert_420'
/home/runner/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: .pio/build/release/lib7b2/libJPEGDEC.a(JPEGDEC.cpp.o):(.literal._ZL10DecodeJPEGP14jpeg_image_tag+0xc): undefined reference to `s3_ycbcr_convert_444'
/home/runner/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: .pio/build/release/lib7b2/libJPEGDEC.a(JPEGDEC.cpp.o): in function `_ZL12JPEGPutMCU22P14jpeg_image_tagii':
/home/runner/work/photos-epaper-frame/photos-epaper-frame/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3726: undefined reference to `s3_ycbcr_convert_420'
/home/runner/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: /home/runner/work/photos-epaper-frame/photos-epaper-frame/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3729: undefined reference to `s3_ycbcr_convert_420'
/home/runner/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: /home/runner/work/photos-epaper-frame/photos-epaper-frame/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3743: undefined reference to `s3_ycbcr_convert_420'
/home/runner/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: /home/runner/work/photos-epaper-frame/photos-epaper-frame/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3744: undefined reference to `s3_ycbcr_convert_420'
/home/runner/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld: .pio/build/release/lib7b2/libJPEGDEC.a(JPEGDEC.cpp.o): in function `_ZL10DecodeJPEGP14jpeg_image_tag':
/home/runner/work/photos-epaper-frame/photos-epaper-frame/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3377: undefined reference to `s3_ycbcr_convert_444'
```

This is the setup of my platformIO project

```
Processing release (platform: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip; board: custom_feather; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/custom_feather.html
PLATFORM: Espressif 32 (51.3.6) > Adafruit Feather ESP32-S3
HARDWARE: ESP32S3 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-builtin, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.0.7 
 - framework-arduinoespressif32-libs @ 5.1.0+sha.632e0c2a9f 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-riscv32-esp @ 12.2.0+20230208 
 - toolchain-xtensa-esp32s3 @ 12.2.0+20230208
```

**Comment by mariusGundersen** [comment]
I believe this is the change that caused it: https://github.com/bitbank2/JPEGDEC/commit/35835517cb30b8bae8dedaecd0b07d45732c0081

Will this only work for the esp32 dev boards?

**Comment by bitbank2** [comment]
sorry, I'll see what happened in the morning

**Comment by bitbank2** [comment]
ok, I pushed a change to add __has_include to make sure it won't try to use the S3 SIMD unless the correct include file exists.

**Comment by mariusGundersen** [comment]
Can you tag it as v1.7.1?

**Comment by bitbank2** [comment]
Did it resolve it completely for you?

**Comment by mariusGundersen** [comment]
I managed to try it directly pointing to the hash, but it still fails.

I'm running on an ESP32-S3, an adafruit feather to be precise. I think the problem is that the initial commit excludes this board, so it does not define the correct stuff even though it's on an esp32-s3

**Comment by bitbank2** [comment]
I think the main problem is that PlatformIO is using an older ESP-IDF inside while Arduino is up to date. Is the C++ file succeeding with the new fix, but the .S files fail? If so, maybe I can go back and protect them with the same change.

**Comment by mariusGundersen** [comment]
Yes, it seems to be the linking that is the problem:

```
Linking .pio\build\release\firmware.elf
c:/users/mariusgundersen/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/release/libd3d/libJPEGDEC.a(JPEGDEC.cpp.o):(.literal._ZL12JPEGPutMCU22P14jpeg_image_tagii+0x4): undefined reference to `s3_ycbcr_convert_420'
c:/users/mariusgundersen/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/release/libd3d/libJPEGDEC.a(JPEGDEC.cpp.o):(.literal._ZL10DecodeJPEGP14jpeg_image_tag+0xc): undefined reference to `s3_ycbcr_convert_444'
c:/users/mariusgundersen/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/release/libd3d/libJPEGDEC.a(JPEGDEC.cpp.o): in function `JPEGPutMCU22(jpeg_image_tag*, int, int)':
C:\dev\6-color-epd/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3728: undefined reference to `s3_ycbcr_convert_420'
c:/users/mariusgundersen/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\dev\6-color-epd/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3731: undefined reference to `s3_ycbcr_convert_420'
c:/users/mariusgundersen/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\dev\6-color-epd/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3745: undefined reference to `s3_ycbcr_convert_420'
c:/users/mariusgundersen/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: C:\dev\6-color-epd/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3746: undefined reference to `s3_ycbcr_convert_420'
c:/users/mariusgundersen/.platformio/packages/toolchain-xtensa-esp32s3/bin/../lib/gcc/xtensa-esp32s3-elf/12.2.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio/build/release/libd3d/libJPEGDEC.a(JPEGDEC.cpp.o): in function `DecodeJPEG(jpeg_image_tag*)':
C:\dev\6-color-epd/.pio/libdeps/release/JPEGDEC/src/jpeg.inl:3379: undefined reference to `s3_ycbcr_convert_444'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\release\firmware.elf] Error 1
```

There is now a different #ifdef in the simd .S files than the jpeg.inl file, that might be the problem.

**Comment by mariusGundersen** [comment]
Any progress on this? For the time being I've locked myself to v1.6.2

**Comment by nslinco** [comment]
Same problem on the Adafruit Qualia ESP32-S3! Downgrading to v1.6.2 works, but would love to be able to use the S3 SIMD in v1.7

**Comment by bitbank2** [comment]
I just pushed an update to put the _has_include protection in the Asm files. Please let me know that it fixes it for you. I won't do an official release until receiving your confirmation.

**Comment by bitbank2** [comment]
If that's an old version of JPEGDEC, that doesn't verify the fix I just did. I believe it's safe now to rebuild on any target processor and only on the ESP32-S3 when the necessary include file exists will it try to build+use the SIMD code.

**Comment by bitbank2** [comment]
oh, so my latest change fixed it for you?

**Comment by mariusGundersen** [comment]
Yes
